import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar
          brandName="MyShop"
          primaryColor="indigo"
          secondaryColor="black"
          mainNavItems={[
            { name: "Home", path: "/" },
            { name: "Shop", path: "/shop" },
            { name: "Deals", path: "/deals" },
          ]}
          accountNavItems={[
            { name: "Login", path: "/login" },
            { name: "Wishlist", path: "/wishlist" },
            { name: "Cart", path: "/cart", isButton: true },
          ]}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
